"""Etapa3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16OgDswu-gUEO6zjDYuuyNwmIzNuXyr-8
"""


#Librerias

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta
from abc import ABC, abstractmethod
import matplotlib.pyplot as plt
from reportlab.pdfgen import canvas
from fpdf import FPDF

"""Base de datos sucios"""

class RegistroLlamada: # Esta clase representa una llamada individual de emergencia, cada uno de sus datos

    def __init__ (self, id_llamada, fecha, zona, tipo, gravedad, es_falsa):
        self.id_llamada = id_llamada
        self.fecha = fecha
        self.zona = zona
        self.tipo = tipo
        self.gravedad = gravedad
        self.es_falsa = es_falsa

#Cada instancia contiene los datos básicos de una llamada.

class GeneradorDatos: # Clase encargada de generar datos simulados incluyendo los errores
    def __init__(self):
      self.zonas_validas = ["Norte", "Sur", "Centro", "Este", "Oeste"]
      self.tipos_validos = ["Accidente", "Incendio", "Enfermedad", "Caida", "Derrame"]
      self.gravedades_validas = [1, 2, 3, 4, 5]

      self.datos = [] # Lista donde se almacenan las llamadas generadas

    def cargar_datos(self, cantidad=1_000_000): #Genera el millon de registros simulados 

        for i in range(cantidad): # Selección random de valores válidos

            zona = random.choice(self.zonas_validas)
            tipo = random.choice(self.tipos_validos)
            gravedad = random.choice(self.gravedades_validas)
            es_falsa = random.choice([True, False])

            fecha = ( # Generación de fecha aleatoria en los últimos 120 días
                datetime.now() -
                timedelta(
                    days=random.randint(0, 120),
                    hours=random.randint(0, 23),
                    minutes=random.randint(0, 59),
                    seconds=random.randint(0, 59)
                )
            ).strftime("%Y-%m-%d %H:%M:%S")



    
            # Se introducen errores intencionalmente para simular datos reales imperfectos


          # Error en zona (5%)
            if random.random() < 0.05:
                zona = random.choice(self.zonas_validas + [None, "descon12313", "error"])



            # Error en tipo (4%)
            if random.random() < 0.04:
                tipo = random.choice(["xd", 999, None])



           # Error en gravedad (6%)
            if random.random() < 0.06:
                gravedad = random.choice([-1, 10, "alta", None])


            # Error en fecha (3%)
            if random.random() < 0.03:
                fecha = random.choice(["ayer", "2025-99-99", None])


            # Caso especial: llamada falsa con gravedad alta (3%)
            if random.random() < 0.03:
                gravedad = 5
                es_falsa = True


            # Crear objeto de llamada
            llamada = RegistroLlamada(i + 1, fecha, zona, tipo, gravedad, es_falsa,
              )
            

            #Se guardan las llamadas en la lista
            self.datos.append(llamada)

        print(f"{cantidad} registros generados")

    def exportar_csv(self): #Convierte los objetos generados en un DataFrame y los exporta a un archivo CSV.
              df = pd.DataFrame([vars(obj) for obj in self.datos])
              df.to_csv("llamadas_sucias.csv", sep=";", index=False, encoding="utf-8")

    def preview(self): #  nos muestra una vista previa del dataset generado.
        df = pd.DataFrame([vars(obj) for obj in self.datos])
        return df.head()

"""limpieza"""

class LimpiarDatos: #Esta clase se encarga de limpiar y preparar los datos. Corrige errores, estandariza valores y deja el dataset listo para análisis.
  def __init__(self, df):
    self.df = df # DataFrame original

     # Valores válidos esperados
    self.zonas_validas = ["Norte", "Sur", "Centro", "Este", "Oeste"]
    self.tipos_validos = ["Accidente", "Incendio", "Enfermedad", "Caida", "Derrame"]
    self.gravedades_validas = [1, 2, 3, 4, 5]
    columnas_necesarias = ["fecha", "zona", "tipo", "gravedad"]



    #Verificación de columnas obligatorias
    for col in columnas_necesarias: 
        if col not in self.df.columns:
            raise ValueError(f"Falta la columna: {col}")

   # ZONAS
  def limpiar_zonas(self):  #Limpia la columna 'zona', Elimina espacios, Corrige formato (Mayúscula inicial), Reemplaza valores inválidos por 'No identificada'

    self.df['zona'] = self.df['zona'].astype(str).str.strip().str.title()

    self.df.loc[
        ~self.df['zona'].isin(self.zonas_validas),
        'zona'
    ] = 'No identificada'


  def resumen_zonas(self): #conteo de zonas
        return self.df['zona'].value_counts()

  def errores_zonas(self): #Cuenta cuántos registros quedaron como inválidos
        return (self.df['zona'] == 'No identificada').sum()


    # -------- TIPOS --------
  def limpiar_tipos(self): #Limpia la columna 'tipo', Corrige formato, Reemplaza valores inválidos por 'No identificado'

    self.df['tipo'] = self.df['tipo'].astype(str).str.strip().str.title()

    self.df.loc[
        ~self.df['tipo'].isin(self.tipos_validos),
        'tipo'
    ] = 'No identificado'




  def resumen_tipos(self): #conteo de tipos de emergencias
        return self.df['tipo'].value_counts()

  def errores_tipos(self): #Cuenta cuántos registros quedaron como inválidos
        return (self.df['tipo'] == 'No identificado').sum()


    #gravedad

  def limpiar_gravedad(self): #Limpia la columna 'gravedad', Convierte a número, Valores fuera de rango (1-5) a 0, NaN a 0

    self.df['gravedad'] = pd.to_numeric(self.df['gravedad'], errors='coerce')

    self.df.loc[
        ~self.df['gravedad'].between(1, 5),
        'gravedad'
    ] = 0

    self.df['gravedad'] = self.df['gravedad'].fillna(0).astype(int)

  def resumen_gravedad(self): #conteo de gravedades
          return self.df['gravedad'].value_counts()

  def errores_gravedad(self): #Cuenta cuántos registros quedaron como inválidos
          return (self.df['gravedad'] == 0).sum()



    #fechas

  def limpiar_fechas(self):
    """
    Limpia la columna 'fecha'
     Convierte a formato datetime
    Valores inválidos a fecha actual
      """


    # convertir a datetime
    self.df['fecha'] = pd.to_datetime(
        self.df['fecha'],
        errors='coerce'
    )

     #rellenar con fecha válida
    fecha_reemplazo = pd.Timestamp.now()

    self.df['fecha'] = self.df['fecha'].fillna(fecha_reemplazo)


  def crear_hora(self):
    """
    Crea una nueva columna 'hora' a partir de la fecha.
    Se usa para análisis de horas pico.
    """

    self.df['hora'] = self.df['fecha'].dt.hour

  def eliminar_duplicados(self):
      """
      Elimina registros duplicados y retorna cuántos se eliminaron
      """
      filas_antes = len(self.df)
      self.df.drop_duplicates(inplace=True)
      filas_despues = len(self.df)
      return filas_antes - filas_despues


  def ordenar_por_fecha(self):
      """
      Ordena los datos cronológicamente
      """

      self.df.sort_values(by='fecha', inplace=True)
      self.df.reset_index(drop=True, inplace=True)


  def exportar_csv(self, nombre="llamadas_limpias.csv"):
      """
      Exporta el dataset limpio a CSV
      """
      self.df.to_csv(nombre, sep=";", index=False, encoding="utf-8")




"""Calcular Estadisticas y tendencias"""

class AnalizadorDatos:
    """
    Esta clase se encarga de extraer información útil del dataset limpio.
    Calcula estadísticas, tendencias y patrones en los datos.
    """

    def __init__(self, df):
        self.df = df

    #Clasificar incidentes
    def clasificar_incidentes(self): #Cuenta cuántos incidentes hay por tipo
        return self.df['tipo'].value_counts()

    # Emergencia más frecuente
    def analizar_frecuencia(self):  # Identifica el tipo de emergencia más frecuente y cuántas veces ocurre.
        conteo = self.df['tipo'].value_counts()
        return conteo.idxmax(), conteo.max()

    # Zona más crítica
    def identificar_zonas_criticas(self): #Identifica la zona con mayor número de emergencias.
        conteo = self.df['zona'].value_counts()
        return conteo.idxmax(), conteo.max()


    def emergencias_por_dia(self): # Agrupa las emergencias por fecha (día)y cuenta cuántas ocurren cada día.
        return self.df.groupby(
            self.df['fecha'].dt.date
        ).size().sort_index()

    def promedio_movil(self, ventana=3): #Calcula el promedio móvil para suavizar los datos. Ayuda a ver tendencias reales eliminando ruido.
        datos = self.emergencias_por_dia()
        return datos.rolling(ventana).mean()

    def tabla_tipo_gravedad(self):
        """
        Crea una tabla cruzada entre tipo de incidente y gravedad.
        Permite ver qué tan graves son los distintos incidentes.
        """
        return pd.crosstab(
            self.df['tipo'],
            self.df['gravedad']
        )

    def tendencia_emergencias(self):
      """
        Calcula la tendencia de emergencias en el tiempo
        usando una regresión lineal simple, calcula:
        pendiente (si sube o baja)
        intercepto
        """
      datos = self.emergencias_por_dia()

      dias = np.arange(len(datos))
      valores = datos.values

      coef = np.polyfit(dias, valores, 1)

      return coef[0], coef[1]  # pendiente, intercepto

    def emergencias_por_hora(self): #Cuenta cuántas emergencias ocurren en cada hora del día. Permite identificar horas pico.
      self.df['hora'] = self.df['fecha'].dt.hour
      return self.df['hora'].value_counts().sort_index()

"""GRAFICAS"""

class Graficas:
  """
  Esta clase se encarga de generar visualizaciones
  a partir de los datos analizados.
  Las gráficas ayudan a interpretar los patrones de forma visual.
  """
  def __init__(self, df):
        self.df = df

  def grafica_gravedad(self):
        """
      Esta clase se encarga de generar visualizaciones
      a partir de los datos analizados en las gravedades
      """

        conteo = self.df['gravedad'].value_counts().sort_index()

        plt.figure(figsize=(10,6))
        plt.bar(conteo.index, conteo.values)


        plt.title("Distribución de gravedad")
        plt.xlabel("Gravedad")
        plt.ylabel("Cantidad de emergencias")

        plt.savefig("gravedad.png")
        plt.show()




  def grafica_zonas(self):
        """
        Genera un gráfico circular (pie chart)
        que muestra la proporción de emergencias por zona.
        """

        conteo = self.df['zona'].value_counts()

        plt.figure(figsize=(10,6))
        plt.pie(
            conteo.values,
            labels=conteo.index,
            autopct='%1.1f%%'
        )

        plt.title("Distribución de zonas")
        plt.savefig("zonas.png")
        plt.show()



  def grafica_tipos(self):
    """
    Genera una gráfica de barras con los tipos de incidentes.
    Permite ver cuáles ocurren con mayor frecuencia.
    """

    conteo = self.df['tipo'].value_counts()

    plt.figure(figsize=(10,6))

    plt.bar(conteo.index, conteo.values)

    plt.title("Tipos de incidentes")
    plt.xlabel("Tipo")
    plt.ylabel("Cantidad")

    plt.xticks(rotation=45)

    plt.tight_layout()

    plt.savefig("tipos.png")
    plt.show()


  def grafica_horas(self):
        """
        Muestra la cantidad de emergencias por hora del día.
        Permite identificar horas pico.
        """

        conteo = self.df['hora'].value_counts().sort_index()

        plt.figure(figsize=(10,6))
        plt.bar(conteo.index, conteo.values)

        plt.xticks(range(24))

        plt.title("Distribución de horas")
        plt.xlabel("Hora")
        plt.ylabel("Cantidad")
        plt.savefig("horas.png")

        plt.show()


  def grafica_promedio_movil(self, serie):
        """
        Grafica el promedio móvil de emergencias.
        Muestra la tendencia suavizada en el tiempo.
        """

        plt.figure(figsize=(10,6))
        plt.plot(serie.index, serie.values, marker='o')

        plt.title("Promedio móvil de emergencias")
        plt.xlabel("Fecha")
        plt.ylabel("Promedio")

        #plt.xticks(rotation=45)
        plt.tight_layout()
        plt.savefig("promedio_movil.png")

        plt.show()


  def graficar_prediccion(self, df_pred):
        """
        Grafica la predicción de emergencias futuras.
        Se basa en datos simulados.
        """

        plt.figure()

        plt.plot(
            df_pred["fecha"],
            df_pred["prediccion"],
            marker='o'
        )

        plt.title("Predicción de emergencias futuras")
        plt.xlabel("Fecha")
        plt.ylabel("Emergencias estimadas")

        #plt.xticks(rotation=45)
        plt.tight_layout()

        plt.savefig("proyeccion.png")

        plt.show()




"""SIMULACION Y PREDICCIÓN"""

class SimuladorDatos:

    def __init__(self, df):
        self.df = df # Se iniciaa con el DataFrame limpio


    def promedio_diario(self):
        """
        Calcula el promedio de emergencias por día.
        Agrupa las llamadas por fecha y obtiene el promedio total.
        """

        emergencias_dia = self.df.groupby(
            self.df['fecha'].dt.date
        ).size()

        return emergencias_dia.mean()




    def predecir(self, dias_futuros=7, ruido=200):
        """
        Genera una predicción de emergencias para los próximos días.
        dias_futuros: cantidad de días a predecir
        ruido: variación aleatoria para simular comportamiento real
        """

        promedio = self.promedio_diario()
        predicciones = []

        for i in range(dias_futuros):

            fecha_futura = (
                datetime.now() + timedelta(days=i+1)
            ).date()

            estimado = round(
                np.random.normal(promedio, ruido)
            )

            predicciones.append([fecha_futura, estimado])

        return pd.DataFrame(
            predicciones,
            columns=["fecha", "prediccion"]
        )



def recomendacion_ambulancias(df, top_n=3):
    """
    Genera recomendaciones de asignación de ambulancias.

    Selecciona las zonas con mayor número de incidentes
    y sugiere aumentar recursos en esas áreas.

    Parámetros:
    - df: DataFrame limpio
    - top_n: número de zonas más críticas a mostrar
    """

    zonas = df['zona'].value_counts().head(top_n) # Obtiene las zonas con más incidentes

    recomendaciones = []

    for zona, cantidad in zonas.items():
        recomendaciones.append(
            f"Asignar más ambulancias en {zona} ({cantidad} incidentes)"
        )

    return recomendaciones


class ReportePDF(FPDF):
    def __init__(self): # Inicializa la clase base FPDF
        super().__init__()

    def header(self):
        
        self.image("Logo.PNG", x=165, y=6, w=40) ## Inserta el logo en la esquina superior derecha

        # Configurar la fuente para el titulo
        self.set_font('Arial', 'B', 16)
        self.set_text_color(31, 119, 180) # Color azul bonito

        #acomoda el texto del titulo 
        self.set_x(25)

        #  Título del Reporte
        self.cell(0, 20, "REPORTE DE EMERGENCIAS Y AMBULANCIAS", ln=True, align='L')

        self.ln(10)



    def titulo_seccion(self, titulo):
      
        self.set_font('Arial', 'B', 14)
        self.set_text_color(31, 119, 180) #color
        self.cell(0, 10, titulo, ln=True)
        self.ln(4)
        self.set_text_color(0, 0, 0) # Regresar a negro

    def texto_normal(self, texto):
    
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 6, texto)
        self.ln(5)

    def tabla_simple(self, dataframe):
       
        self.set_font('Arial', 'B', 10)


        # encabezados de la tabla
        for col in dataframe.columns:
            self.cell(90, 8, str(col), border=1)
        self.ln()

        self.set_font('Arial', '', 10)


        # filas
        for index, row in dataframe.iterrows():
            for val in row:
                self.cell(90, 8, str(val), border=1)
            self.ln()

def generar_reporte_pdf(df, analizador, eliminados):
     

      pdf = ReportePDF()

      pdf.set_margins(left=15, top=20, right=15)   # márgenes generales


      pdf.add_page()

      pdf.ln(1)



# Inicio
      pdf.titulo_seccion("Resumen General")

      pdf.texto_normal(
    "Este reporte presenta el analisis estadistico de "
    "las llamadas de emergencia recibidas por el sistema "
    "de ambulancias. La informacion incluye clasificacion "
    "de incidentes, zonas criticas, niveles de gravedad "
    "y comportamiento de las emergencias."
)

# ESTADÍSTICAS
      pdf.titulo_seccion("Estadisticas Generales")

      total_llamadas = len(df)

      tipo_frecuente, cantidad_tipo = analizador.analizar_frecuencia()

      zona_critica, cantidad_zona = analizador.identificar_zonas_criticas()

      pdf.texto_normal(
    f"Total de llamadas analizadas: {total_llamadas}\n"
    f"Emergencia mas frecuente: {tipo_frecuente} ({cantidad_tipo})\n"
    f"Zona mas critica: {zona_critica} ({cantidad_zona})\n"
    f"Registros duplicados eliminados: {eliminados}"
)

# TABLA INCIDENTES
      pdf.titulo_seccion("1. Incidentes más frecuentes")

      pdf.texto_normal(
    "El analisis realizado muestra las estadisticas de los tipos de incidentes mas frecuentes acompañados de una gráfica"

    )


      tabla_incidentes = (
        analizador.clasificar_incidentes()
        .reset_index()
)

      tabla_incidentes.columns = [
    "Tipo de Incidente",
    "Cantidad"
]


      pdf.tabla_simple(tabla_incidentes)


#grafica 1 

      pdf.set_font("Arial", "B", 13)

      pdf.cell(
    200,
    10,
    ln=True
)
#imagen de la grafica
      pdf.image("tipos.png", x=70,  w=170)
      pdf.ln(10)

# TABLA ZONAS
      pdf.titulo_seccion("2. Zonas con mas indicentes")

      tabla_zonas = (
      df['zona']
    .value_counts()
    .reset_index()
)

      tabla_zonas.columns = [
    "Zona",
    "Llamadas"
]

      pdf.tabla_simple(tabla_zonas)

#grafica 2
      pdf.texto_normal(
    "La gráfica nos muestra la información de la tabla representada con porcentajes e indicandonos tambien los datos invallidos"

    )
      pdf.set_font("Arial", "B", 13)

      pdf.cell(
    200,
    10,
    ln=True
)
#imagen 
      pdf.image("zonas.png", x=25, w=190)

      pdf.ln(10)



      pdf.add_page()
#horas

      pdf.titulo_seccion("3. Horas con mas incidentes")

      pdf.texto_normal(
    "Presentamos las horas en las que mas ocurrieron incidentes en un formato 24h notando la tendencia en las 00:00 horas, este análisis especial para identificar exactamente los momentos del día donde se deben preparar las ambulancias"

    )


      pdf.set_font("Arial", "B", 13)

      pdf.cell(
    200,
    10,
    ln=True
)
#imagen
      pdf.image("horas.png", x=20, w=170)

      pdf.add_page()


#gravedad

      pdf.titulo_seccion("4. Triage de Emergencias")
      pdf.texto_normal(
    "Presentamos el triage en el que mas se clasificaron las emergencias, mostrando 0 como las emergencias que no se identificaron en los datos "

    )


      pdf.set_font("Arial", "B", 13)

      pdf.cell(
    200,
    10,
    ln=True
)

      pdf.image("gravedad.png", x=25, w=170)

      pdf.add_page()


#Proyecciones

      pdf.titulo_seccion("5. Promedio Movil")
      pdf.texto_normal(
    "Este promedio evalua las emergencias de los ultimos 3 días para encontrar un balance entre todas las emergencias"

    )

#grafica 3

      pdf.set_font("Arial", "B", 13)

      pdf.cell(
    200,
    10,
    ln=True
)
#imagen
      pdf.image("promedio_movil.png", x=25, w=170)

      pdf.ln(10)


#Proyeccion

      pdf.add_page()
      pdf.titulo_seccion("6. Proyección")
      pdf.texto_normal(
    "El analisis realizado demuestra una proyección futura, los proximos 7 días se pueden presentar las siguientes cantidades de emergencias"

    )

#grafica 3

      pdf.set_font("Arial", "B", 13)

      pdf.cell(
    200,
    10,
    ln=True
)

      pdf.image("proyeccion.png", x=50, w=130)

      pdf.ln(10)


# CONCLUSIÓN
      pdf.titulo_seccion("Conclusiones")

      pdf.texto_normal(
    "El analisis realizado demuestra una alta actividad "
    "de emergencias en zonas urbanas especificas. "
    "El proceso de limpieza de datos permitio mejorar "
    "la calidad de la informacion utilizada para "
    "predicciones y toma de decisiones operativas. "
    "Para atender estas necesidades, se hacen las siguientes recomendaciones"
)
      
      #Ambulancias
      pdf.add_page()
      pdf.titulo_seccion("Recomendaciones")
      
      recs = recomendacion_ambulancias(df)
      for r in recs:
          pdf.texto_normal(f"- {r}")
      


# GUARDAR PDF
      print("PDF generado correctamente")
      pdf.output("Reporte_Emergencias.pdf")
